/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BelumBayarRouteImport } from './routes/belum-bayar'
import { Route as PusatRouteImport } from './routes/pusat'
import { Route as ApiPublicCleanupRouteImport } from './routes/api/public/cleanup'
import { Route as ApiPublicLatestNewsRouteImport } from './routes/api/public/latest-news'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelumBayarRoute = BelumBayarRouteImport.update({
  id: '/belum-bayar',
  path: '/belum-bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const PusatRoute = PusatRouteImport.update({
  id: '/pusat',
  path: '/pusat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCleanupRoute = ApiPublicCleanupRouteImport.update({
  id: '/api/public/cleanup',
  path: '/api/public/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLatestNewsRoute = ApiPublicLatestNewsRouteImport.update({
  id: '/api/public/latest-news',
  path: '/api/public/latest-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/pusat': typeof PusatRoute
  '/api/public/cleanup': typeof ApiPublicCleanupRoute
  '/api/public/latest-news': typeof ApiPublicLatestNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/pusat': typeof PusatRoute
  '/api/public/cleanup': typeof ApiPublicCleanupRoute
  '/api/public/latest-news': typeof ApiPublicLatestNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/pusat': typeof PusatRoute
  '/api/public/cleanup': typeof ApiPublicCleanupRoute
  '/api/public/latest-news': typeof ApiPublicLatestNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/belum-bayar'
    | '/pusat'
    | '/api/public/cleanup'
    | '/api/public/latest-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/belum-bayar'
    | '/pusat'
    | '/api/public/cleanup'
    | '/api/public/latest-news'
  id:
    | '__root__'
    | '/'
    | '/belum-bayar'
    | '/pusat'
    | '/api/public/cleanup'
    | '/api/public/latest-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelumBayarRoute: typeof BelumBayarRoute
  PusatRoute: typeof PusatRoute
  ApiPublicCleanupRoute: typeof ApiPublicCleanupRoute
  ApiPublicLatestNewsRoute: typeof ApiPublicLatestNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belum-bayar': {
      id: '/belum-bayar'
      path: '/belum-bayar'
      fullPath: '/belum-bayar'
      preLoaderRoute: typeof BelumBayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pusat': {
      id: '/pusat'
      path: '/pusat'
      fullPath: '/pusat'
      preLoaderRoute: typeof PusatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleanup': {
      id: '/api/public/cleanup'
      path: '/api/public/cleanup'
      fullPath: '/api/public/cleanup'
      preLoaderRoute: typeof ApiPublicCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/latest-news': {
      id: '/api/public/latest-news'
      path: '/api/public/latest-news'
      fullPath: '/api/public/latest-news'
      preLoaderRoute: typeof ApiPublicLatestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelumBayarRoute: BelumBayarRoute,
  PusatRoute: PusatRoute,
  ApiPublicCleanupRoute: ApiPublicCleanupRoute,
  ApiPublicLatestNewsRoute: ApiPublicLatestNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
